name: 'Automatic Versioning'
description: |
  This action provides the ability to automatically bump the version number inside the package.json file of a Javascript project
  and update a CHANGELOG.md file
author: 'mx51'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'
