name: 'Automatic Versioning'
description: |
  This action provides the ability to automatically bump the version number inside the package.json file of a Javascript project
  and update a CHANGELOG.md file
author: 'mx51'
inputs:
  github_token: # change this
    required: true
    description: 'input description here'
  project_dir: # change this
    required: false
    description: 'input description here'
    default: ./
  branch: # change this
    required: false
    description: 'input description here'
  add_changelog_entry:
    required: true
    description: 'input description here'
    default: false
  changelog_filename: # change this
    required: false
    description: 'input description here'
  changelog_msg: # change this
    required: false
    description: 'input description here'
  major_label:
    required: false
    description: 'A label associated with a major change'
    default: 'pr:major'
  minor_label:
    required: false
    description: 'A label associated with a minor change'
    default: 'pr:minor'
  patch_label:
    required: false
    description: 'A label associated with a patch change'
    default: 'pr:patch' 


runs:
  using: 'node16'
  main: 'dist/index.js'
